### ISSUE TITLE
3D audio doesn't work

### ISSUE THREAD

**Issue by ericvrp** [JackM36/Eazy-Sound-Manager#19]
All audiosources are added as components to the EasySoundManager gameObject. So how are audiosources at various locations supposed to work when there is only one EasySoundManager position?

And secondly: the position of EasySoundManager doesn't seem to be set to the sourceTransform.position. The 3D support seems untested.

**Comment by JackM36** [comment]
Hello @ericvrp

Some overloads of the Play functions needs you to pass a source transform. When you do, the AudioSource component will be attached on that transform instead of the EazySoundManager one.

For example, for sound effects you could use this:
http://www.hellmadegames.com/projects/eazy-sound-manager/docs/api-reference/html/M_Hellmade_Sound_EazySoundManager_PlaySound_3.htm

Is this actually how you are using it and it still does not work as intended?

**Comment by ericvrp** [comment]
Yes, I'm doing
> EazySoundManager.PlaySound(audioClip, volume, loop, gameObject.transform);
but the AudioSource gets attached to EasySoundManager instead of to gameObject.

**Comment by JackM36** [comment]
Bug is now fixed, thanks for reporting @ericvrp 

If you still experience this bug, please reopen this issue.

**Comment by ericvrp** [comment]
When will a new version be in the assetstore?

**Comment by JackM36** [comment]
I already submitted the update, It should be live in a few days.

**Comment by JackM36** [comment]
Update is now live in the Asset store.
